### PR TITLE
feat: Add missing topologySpreadConstraints options in kubernetes_deployment

### PR DESCRIPTION
**Pull request by alexlokshin-czi**
### Acceptance tests
- [ ] Have you added an acceptance test for the functionality being added?
- [ ] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/CHANGELOG.md):

```release-note
...
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Review by arybolovlev — CHANGES_REQUESTED** [review]
Hi @alexlokshin-czi,

I have left a few comments, could you please address them and let me know once it is done? Then I will push changes for the test.

Thanks!

**Comment by arybolovlev** [comment]
Please sing the CLA: https://github.com/hashicorp/terraform-provider-kubernetes/pull/2327#issuecomment-1775527668. Thanks!

**Comment by BBBmau** [comment]
Any update on this? @alexlokshin-czi

**Comment by appilon** [comment]
Superseded in #2429

**Pull request closed without merging**
