### PR TITLE
r/ingress_class - new resource

### LINKED ISSUE #1217: Please provide a kubernetes_ingress_class resource
### Description

Kubernetes 1.18 has a new document called IngressClass which is required for ingress configuration.

### Potential Terraform Configuration

```hcl
resource "kubernetes_ingress_class" {
  metadata {
    name = "external-lb"
  }
  spec {
    controller = "example.com/ingress-controller"
    parameters = {
        apiGroup = "k8s.example.com/v1alpha"
        kind = "IngressParameters"
        name = "external-lb"
    }
  }
}
```

### References

https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### LINKED ISSUE #1218: Enhance kubernetes_ingress with ingress_class_name attribute
### Description
Please add an ingress_class_name to the kubernetes_ingress resource, as it is specified at Kubernetes 1.18.

### Potential Terraform Configuration

```hcl
resource "kubernetes_ingress" "example" {
  ...
  spec {
    ingress_class_name = "external-lb"
    tls {
        ...
    }
    ...
  }
}
```

### References
https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#putting-it-all-together

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by DrFaust92**
### Acceptance tests
- [x] Have you added an acceptance test for the functionality being added?
- [x] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccKubernetesIngressClass_'
--- PASS: TestAccKubernetesIngressClass_basic (2.98s)
--- PASS: TestAccKubernetesIngressClass_parameters (4.78s)
--- PASS: TestAccKubernetesIngressClass_parameters_apiGroup (4.82s)
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/CHANGELOG.md):

```release-note
resource_kubernetes_ingress_class - new resource
```

### References
Closes #1217
Closes #1218

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Comment by philicious** [comment]
any ETA when this might be ready ?  watching the PR now for a while and waiting for a release :) 👍

**Comment by lkishalmi** [comment]
Waiting for this as well.

**Comment by philicious** [comment]
@DrFaust92 is there anything you know of that is blocking this PR to be merged ? 

can we maybe get a reviewers comment too please ! @dak1n1 @alexsomesan 

let me know if there is sth you could need help with to get this PR ready/merged !

**Comment by lkishalmi** [comment]
@alexsomesan is there anything keeping this PR from being merged?

**Comment by nickbruun** [comment]
Is there anything the community can do to drive this to be merged?

**Comment by philicious** [comment]
@dak1n1 @alexsomesan @jrhouston pinging you as you have approved previous PRs and seem to be maintainers. could you pls shed some light how the community can get this PR merged ?

**Comment by philicious** [comment]
@alexsomesan and @jrhouston I see you are active commiters so I yet again try to get your help on this PR: what would be missing to get this one merged ? 
its open for so long and becoming a a real bummer to not IngressClass supported by k8s provider yet 👎

**Comment by jrhouston** [comment]
Apologies for the delay here @philicious @lkishalmi @DrFaust92 – I have made a few fixes (some validation, docs fixes, and the resource ID didn't need to be namespaced) to this branch, and will merge once the the checks pass.

**Comment by philicious** [comment]
thanks alot @jrhouston !!!

**Pull request merged**
