### PR TITLE
r/ingress - support `path_type`

### LINKED ISSUE #1023: Add path_type to kubernetes_ingress
### Description

I am fairly new to kubernetes so I can't suggest how this can be done but we'd really like the ability to specify path_type as part of rule within a kubernetes_ingress. 

### Potential Terraform Configuration

In Yaml this would look like this:
```yaml

- path: /api/app.api
        pathType: Prefix
        backend:
          serviceName: appapi
          servicePort: 80


```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### LINKED ISSUE #1207: Ingress resource docs are inconsistent on path being a regex
https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/ingress#path says that path can be a regular expression. However, I believe this depends on what ingress controller actually acts on the ingress? I'm new to Kubernetes, but according to https://v1-18.docs.kubernetes.io/docs/concepts/services-networking/ingress/ the default value of `pathType` is `ImplementationSpecific`. Perhaps the Terraform docs should reflect this? Also, the example at the top says `path = "/app1/*"` which is unlikely to be what you want if that is actually a regex.

### Terraform Version, Provider Version and Kubernetes Version
Docs for kubernetes provider v2.0.3
Kubernetes version: 1.18

### Affected Resource(s)
kubernetes_ingress

### Terraform Configuration Files
```hcl
resource "kubernetes_ingress" "ze_ingress" {
  metadata {
    name = "ze-ingress"
  }
  spec {
    rule {
      host = "ze.hostname"
      http {
        path {
          backend {
            service_name = "ze-service"
            service_port = "http"
          }
          path = "/*" # Inspired by example at the top of kubernetes_ingress page
        }
      }
    }
  }
}
```

### Expected Behavior
I think I would have expected the docs to mention that this value is implementation dependent. Of course, you could also see this as a feature request to expose `pathType` :)

### Actual Behavior
I read
> path - (Required) A string or an extended POSIX regular expression as defined by IEEE Std 1003.1, (i.e this follows the egrep/unix syntax, not the perl syntax) matched against the path of an incoming request. Currently it can contain characters disallowed from the conventional \"path\" part of a URL as defined by RFC 3986. Paths must begin with a '/'. If unspecified, the path defaults to a catch all sending traffic to the backend."

### PR DESCRIPTION
**Pull request by DrFaust92**
### Description

Also slightly refactored acceptance tests

### Acceptance tests
- [x] Have you added an acceptance test for the functionality being added?
- [x] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccKubernetesIngress_'
--- PASS: TestAccKubernetesIngress_basic (4.97s)
--- PASS: TestAccKubernetesIngress_pathType (5.16s)
--- PASS: TestAccKubernetesIngress_TLS (4.96s)
--- PASS: TestAccKubernetesIngress_InternalKey (6.64s)
--- PASS: TestAccKubernetesDataSourceIngress_basic (4.04s)
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/CHANGELOG.md):

```release-note
resource_kubernetes_ingress - add support for `path_type`
data_source_kubernetes_ingress - add support for `path_type`
```

### References
Closes #1023
Closes #1207

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Comment by mcfedr** [comment]
Also closes https://github.com/hashicorp/terraform-provider-kubernetes/issues/1319

**Comment by joelsdc** [comment]
Any updates? Any idea when this will be merged?

**Comment by mdtusz** [comment]
Is there anything still blocking this PR that needs assistance? Using `pathType` seems to be a fairly common thing so it would be lovely to get this landed!

**Comment by mcfedr** [comment]
I guess this is also related to https://github.com/hashicorp/terraform-provider-kubernetes/pull/1408 - which seems to add pathType and also a full api update

**Pull request closed without merging**
