### PR TITLE
Fix waitForDeploymentReplicasFunc not waiting for rollout when generation > 1

### PR DESCRIPTION
**Pull request by davidfischer-ch**
### Description

Enabling "wait_for_rollout" is not working as expected when resource is being updated (basically when generation > 1).
I fixed the function basically and split the **if** to make the code more readable and prevent mistakes.

I added a non retryable error in case observed generation is greater than generation.
I do not expect it to happen, so the code checks it for us.

### Acceptance tests
- [no] Have you added an acceptance test for the functionality being added?
- [no] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/CHANGELOG.md):

```release-note
NONE
```

### References

https://github.com/hashicorp/terraform-provider-kubernetes/issues/1036

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Comment by jamesgunnfiveai** [comment]
I think this PR should link this issue: https://github.com/hashicorp/terraform-provider-kubernetes/issues/1036

**Comment by maur1th** [comment]
I've tested it out and it does seem to fix https://github.com/hashicorp/terraform-provider-kubernetes/issues/1036.
Can't wait to have this released. Thanks a lot!

**Comment by maur1th** [comment]
What's the process to get this reviewed?

**Comment by tjs-intel** [comment]
@alexsomesan I've seen your approval on some recent reviews, how can we get this change in a future release?

**Review by arybolovlev — APPROVED** [review]

**Pull request merged**
