### PR TITLE
Update kubernetes to v1.28.6

### PR DESCRIPTION
**Pull request by appilon**
### Description
Update kubernetes and remove replace directives.

### Acceptance tests
- [ ] Have you added an acceptance test for the functionality being added?
- [x] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
$ make testacc
...
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/CHANGELOG.md):

```release-note:note
Bump Kubernetes dependencies from x.27.8 to x.28.6.
```

### References
N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Comment by arybolovlev** [comment]
Can you please add a changelog file `.changelog/2404.txt` to reflect the changes in this PR in the upcoming release note?

Something like this:

~~~
```release-note:note
Bump Kubernetes dependencies from x.27.8 to x.28.6.
```
~~~

Thanks!

**Comment by appilon** [comment]
@arybolovlev I ran the tests locally against a manually pinned k8s 1.28 cluster in kind. I was going to pin the version in the PR, but then I realized it seems like the `kind` version can be set as an input variable, and this is sort of the defacto way of setting the version of the k8s cluster. Problem is kind 0.21 is not released yet so the acceptance tests can't currently be set to k8s 1.28.

**Comment by arybolovlev** [comment]
> @arybolovlev I ran the tests locally against a manually pinned k8s 1.28 cluster in kind. I was going to pin the version in the PR, but then I realized it seems like the `kind` version can be set as an input variable in GH actions, and this is sort of the defacto way of setting the version of the k8s cluster. Problem is kind 0.21 is not released yet so the acceptance tests can't currently be set to k8s 1.28.

That is fine. They are backward compatible anyway. This issue with KinD will be fixed soon too. In the meantime, AKS, EKS, and GKE run on 1.28, you can run them manually or wait for the next day after the merge, and they will be run nightly.

Thanks!

**Review by arybolovlev — APPROVED** [review]
Thanks, Alex! 🚀

**Comment by appilon** [comment]
@arybolovlev Do i need to bump the default version of k8s for the GKE/AWS/Azure clusters? I see 1.27 referenced as the default in a few places?

**Pull request merged**
