### PR TITLE
limit_range: validate quantities

### PR DESCRIPTION
**Pull request by bendrucker**
### Description

This PR validates the fields in a LimitRange, checking that each map is suitable as a [`v1.ResourceList`](https://godoc.org/k8s.io/api/core/v1#ResourceList). It ensures that invalid quantities are checked by Terraform during validation, rather than failing later on the server with:

```
quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
```

This brings it up to parity with ResourceQuota and other resources that use this validator. Previously, a simple typo like `1 Gi` (whitespace) did not raise an error until apply time.

### Acceptance tests
- [ ] Have you added an acceptance test for the functionality being added?
- [x] Have you run the acceptance tests on this branch? (If so, please include the test log in a gist)

<details>
<summary>
<strong>Output: </strong><code>TESTARGS="-run LimitRange" make testacc</code>
</summary>

```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test "./kubernetes" -v -run LimitRange -timeout 120m
=== RUN   TestAccKubernetesLimitRange_basic
--- PASS: TestAccKubernetesLimitRange_basic (1.06s)
=== RUN   TestAccKubernetesLimitRange_empty
--- PASS: TestAccKubernetesLimitRange_empty (0.40s)
=== RUN   TestAccKubernetesLimitRange_generatedName
--- PASS: TestAccKubernetesLimitRange_generatedName (0.42s)
=== RUN   TestAccKubernetesLimitRange_typeChange
--- PASS: TestAccKubernetesLimitRange_typeChange (0.65s)
=== RUN   TestAccKubernetesLimitRange_multipleLimits
--- PASS: TestAccKubernetesLimitRange_multipleLimits (0.39s)
=== RUN   TestAccKubernetesLimitRange_importBasic
--- PASS: TestAccKubernetesLimitRange_importBasic (0.52s)
PASS
ok  	github.com/hashicorp/terraform-provider-kubernetes/kubernetes	5.023s
```

</details>

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Comment by bendrucker** [comment]
Hey, just wanted to bump this once, should be a simple/easy improvement.

**Comment by bendrucker** [comment]
Closing this based on inactivity. If there's any interest in merging feel free to use it!

**Comment by aareet** [comment]
If it's alright with you, I'll reopen this - we'll take it over if we decide to use it, but closing it takes it off our radar

**Comment by bendrucker** [comment]
Ok, it does leave it in my open PR list indefinitely, which is why I close anything that doesn't have any progress towards getting merged. Seems like and easy, low risk enhancement, I'll leave it up for a bit longer.

**Comment by bendrucker** [comment]
Any interest in this? Since it's been about a year and it's a minor contribution I'll plan to close this out again a week from now. The code is free to use but I prefer to not have PRs open indefinitely.

**Pull request closed without merging**
