### PR TITLE
Make enableServiceLinks configurable from the pod specification

### PR DESCRIPTION
**Pull request by MathyV**
### Description

I stumbled into resource problems on our cluster because enableServiceLinks is enabled by default, so I wanted to disable it but Terraform is not able to do so. I found issue #693 which talks about this lack of functionality. I created an implementation that seems to work by copying and adapting the host_ipc parameter.

One thing that I'm not sure I handled correctly is the default value. Might be a lack of comprehension from my side as this is the first time I take a dive into the terraform source. 

It seems if the value was never sent to k8s it's not in the pod spec and in.EnableServiceLinks == nil. In that case for k8s it means that the value is set to true. I thought that setting the Default in the schema would be enough to make sure that att["enable_service_links"] would be set to true elsewhere in the code but this did not work.

The only way I got it working was by adding the else clause in structures_pod.go. The code now works for me in all cases, I tested changing both pre-change pods and post-change pods, with true, false and no value specified.

### Acceptance tests

I did not create additional tests as host_ipc doesn't have them either.

### References

https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#accessing-the-service

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#pod-v1-core

Issue #693

### CODE REVIEW

**Comment by DrFaust92** [comment]
@MathyV, can you rebase and resolve conflicts for this PR? really would like to have this feature

**Comment by MathyV** [comment]
> @MathyV, can you rebase and resolve conflicts for this PR? really would like to have this feature

@DrFaust92 done

**Comment by DrFaust92** [comment]
Thanks, looks good. Can you also add an acceptance test for this?

**Comment by MathyV** [comment]
> Thanks, looks good. Can you also add an acceptance test for this?

I will have a look, not sure how to do it though, like I said I just copied stuff from host_ipc and that one didn't have tests so I figured this one might not need one too.

**Comment by DrFaust92** [comment]
@MathyV, are you still looking into this? i can fork from your branch and add the needed tests

**Comment by MathyV** [comment]
I didn't have time yet to look into it, won't have time until next week,
but feel free to do so if you want it faster.

**Comment by DrFaust92** [comment]
Opened #975 that uses original branch + added tests

**Comment by MathyV** [comment]
Closing this in favour of the new PR.

**Pull request closed without merging**
