### PR TITLE
Feature/add addresses info to nodes

### PR DESCRIPTION
**Pull request by axcosta**
### Description

This adds the addresses information for the `data.kubernetes_nodes`.

### Acceptance tests
- [X] Have you added an acceptance test for the functionality being added?
- [X] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
$ make testacc TESTARGS='run=TestAccKubernetesDataSourceNodes.*'
==> Checking that code complies with gofmt requirements...
go vet .
TF_ACC=1 go test "/home/axcosta/go/src/github.com/hashicorp/terraform-provider-kubernetes/kubernetes" -v -run=TestAccKubernetesDataSourceNodes.* -timeout 3h
=== RUN   TestAccKubernetesDataSourceNodes_basic
--- PASS: TestAccKubernetesDataSourceNodes_basic (11.96s)
PASS
ok      github.com/hashicorp/terraform-provider-kubernetes/kubernetes   11.992s
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/CHANGELOG.md):

```release-note
Added addresses information for the `data.kubernetes_nodes`
```

### References

#2124 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Comment by BBBmau** [comment]
Hello, thank you for opening this PR @axcosta! Could you also add documentation of this new attribute?

**Comment by axcosta** [comment]
> Hello, thank you for opening this PR @axcosta! Could you also add documentation of this new attribute?

Hello @BBBmau, my first PR here. What kind of documentation is necessary, could you please advise?

**Comment by BBBmau** [comment]
sure thing @axcosta , since `addresses` is a  new attribute in the schema, you'll want to include it as part of the [docs](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/data-sources/nodes)

You can edit the docs [here](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/website/docs/d/nodes.html.markdown)

**Review by BBBmau — APPROVED** [review]
LGTM! Thank you for contributing!

**Pull request merged**
