### PR TITLE
Feature: Custom Resource

### PR DESCRIPTION
**Pull request by timthesinner**
Looking to get an assessment on where I am headed with this.  Resource naming, constructs, ETC.  The biggest architectural change is that I converted to using interfaces when interacting with K8S instead of a formal type.  I needed to extend the base `kubernetes.Clientset` in order to enable a custom resource client.

### Resource state management
We need to handle state diff between K8S, TF, and Desired.  This was accomplished by adding `transient` fields to the computed `spec` field dynamically from a custom diff function.  Take a look at the diff function [here](https://github.com/timthesinner/terraform-provider-kubernetes/blob/f-custom-resource/kubernetes/resource_custom.go#L140). Here are what each of the transient fields mean:
- `transient-delete` is a field that will get removed (may have been added out of band)
- `transient-add` is a field that will get added (may have been deleted out of band)
- `transient-update` is a field that will get replaced (may have been modified out of band)

Notes:
- Using the flattened dict and keyed prefix is real clean when building the `PATCH` options.
   - `path` is replace the key prefix with `/spec/` and replace all `.` with `/`
   - `value` is `spec[key - prefix]`
   - `op` is the prefix type (a constant)
- We end up writing the spec from the returned response from K8S so these transient fields are never persisted into tfstate.  
- The diff accounts for updates to the `yaml` field
- Updating K8S by hand, and then updating `yaml` to match will result in a delta to the `yaml` field, but no update ops will be sent to K8S.

I have been doing all my testing with a terraform that creates a `ClusterIssuer` using the yaml template below.  
```
resource "kubernetes_generic" "test" {
    api_version = "certmanager.k8s.io/v1alpha1"
    kind ="ClusterIssuer"

    metadata {
        name = "terraform-example"
    }

    yaml = <<EOF
acme:
    email: email
    server: server
    privateKeySecretRef:
        name: secret-dev2
    dns01:
        providers:
        - name: route53
        route53:
            region: region
            hostedZoneID: zoneId
            accessKeyID: accessKey
            secretAccessKeySecretRef:
                name: secret
                key: secret-access-key
EOF
}
```

#215

### CODE REVIEW

**Comment by bukzor** [comment]
What's the state of this branch? Is it still as described in OP (no updates)?

I'm very excited as a potential user of something like this. Would you advise against attempting to use this branch for "real work"?

**Comment by mmalecki** [comment]
This feels similar to #195, which resulted in a separate plugin being created: https://github.com/lawrencegripper/terraform-provider-kubernetes-yaml

**Comment by timthesinner** [comment]
I was looking for initial feedback on naming conventions ETC, didn't hear anything so its been on the back burner for me.

The branch needs tests and I need to work through the diff/update logic to conform to the JSONPatch format that the API expects.

If I get some time tomorrow I can wrap up that last bit and it will be fully functional minus tests.

**Comment by yacut** [comment]
@timthesinner any update on this?

**Comment by timthesinner** [comment]
@yacut, @bukzor  at this point create, edit, and delete are all working.  Out of band changes to K8S are also handled with a custom diff.
@alexsomesan As the primary on this feature for TF 0.12 could you take a look at this, I think I got a decent UX between TF/K8S/Desired states using a transient key in the state map.

After I applied the TF configuration I manually updated the resource, this is the output of `$ kubectl get clusterissuer terraform-example -o yaml`
```apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"certmanager.k8s.io/v1alpha1","kind":"ClusterIssuer","metadata":{"annotations":{},"name":"terraform-example"},"spec":{"acme":{"dns01":{"providers":[{"name":"route59"}],"route53":{"region":"region","secretAccessKeySecretRef":{"key":"secret-access-key","name":"secret"}}},"email":"email","privateKeySecretRef":{"name":"secret-dev3"},"server":"server","server2":"test"}}}
  clusterName: ""
  creationTimestamp: 2019-02-17T23:49:06Z
  generation: 0
  name: terraform-example
  namespace: ""
  resourceVersion: "63297229"
  selfLink: /apis/certmanager.k8s.io/v1alpha1/terraform-example
  uid: 9c94369d-330e-11e9-b5ef-0e204540d6a2
spec:
  acme:
    dns01:
      providers:
      - name: route59
      route53:
        region: region
        secretAccessKeySecretRef:
          key: secret-access-key
          name: secret
    email: email
    privateKeySecretRef:
      name: secret-dev3
    server: server
    server2: test
```

Note on the transient fields, these are added into the spec dynamically from a custom diff function.  We end up writing the spec from the returned response from K8S so these transient fields are never persisted into tfstate.  This transient mapping is necessary, if we just rely on the internal state of the spec we cannot reliably diff between K8S state, TF state, and desired state.  Here are what each of the transient fields mean:
- `transient-delete` is a field that was configured out of band from TF, it will get removed
- `transient-add` is a field that will get added (may have been deleted out of band)
- `transient-update` is a field that will get replaced (may have been modified out of band)

After running `terraform apply`
```
kubernetes_generic.test: Refreshing state... (ID: certmanager.k8s.io/v1alpha1/terraform-example)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ kubernetes_generic.test
      spec.%:                                               "10" => "15"
      spec.transitent-add.acme.dns01.route53.accessKeyID:   "" => "accessKey"
      spec.transitent-add.acme.dns01.route53.hostedZoneID:  "" => "zoneId"
      spec.transitent-delete.acme.server2:                  "" => "'test' --> ''"
      spec.transitent-update.acme.dns01.providers.0.name:   "" => "'route59' --> 'route53'"
      spec.transitent-update.acme.privateKeySecretRef.name: "" => "'secret-dev3' --> 'secret-dev-test'"


Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by Tazer** [comment]
@timthesinner just tried running your branch :) but go into a "loop" 

Cause first it complained about 
`kubernetes_generic.cloudflare-issuer: Issuer.certmanager.k8s.io "cloudflare-issuer" is invalid: metadata.namespace: Required value`

Code looks like this
```
resource "kubernetes_generic" "cloudflare-issuer" {
    api_version = "certmanager.k8s.io/v1alpha1"
    kind ="Issuer"

    metadata {
        name = "cloudflare-issuer"
    }

    yaml = <<EOF
  acme:
    email: xxx
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: xxx
    dns01:
      providers:
        - name: prod-clouddns
          cloudflare:
            email: xxx
            apiKeySecretRef:
              name: xxx
              key: api-key
EOF
}
```

Then when I added namespace property I got  `Error: kubernetes_generic.cloudflare-issuer: metadata.0: invalid or unknown key: namespace`

Config:
```
resource "kubernetes_generic" "cloudflare-issuer" {
    api_version = "certmanager.k8s.io/v1alpha1"
    kind ="Issuer"

    metadata {
        name = "cloudflare-issuer"
        namespace = "default"
    }

    yaml = <<EOF
  acme:
    email: xxx
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: xxx
    dns01:
      providers:
        - name: prod-clouddns
          cloudflare:
            email: xxx
            apiKeySecretRef:
              name: xxx
              key: api-key
EOF
}
```

**Comment by timthesinner** [comment]
@Tazer good find, I forgot to test generic resources in namespaces.  I added the field to the metadata schema and updated the create logic to support custom resources that belong in a namespace.  

Please let me know if you run into any additional issues.

**Comment by Tazer** [comment]
@timthesinner tried some more today adding custom resources. 

Got into "unexpected EOF" 

my terraform resource
```
resource "kubernetes_generic" "cr-clusterissuer" {
  api_version = "apiextensions.k8s.io/v1beta1"
  kind        = "CustomResourceDefinition"

  metadata {
    name = "clusterissuers.certmanager.k8s.io"

    labels {
      app = "cert-manager"
    }
  }

  yaml = <<EOF
  group: certmanager.k8s.io
  version: v1alpha1
  names:
    kind: ClusterIssuer
    plural: clusterissuers
  scope: Cluster
EOF
}
```

YAML file ( that I try to write with the kubernetes generic resource )
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterissuers.certmanager.k8s.io
  labels:
    app: cert-manager
spec:
  group: certmanager.k8s.io
  version: v1alpha1
  names:
    kind: ClusterIssuer
    plural: clusterissuers
  scope: Cluster
```

Maybe I'm doing something wrong?

**Comment by timthesinner** [comment]
@Tazer it looks like your trying to create a CustomResourceDefinition on K8S and that's failing (error messages are not clean just yet)probably because that CRD already exists for you.

The problem is coming from your kind/api_versions are:
```
  api_version = "apiextensions.k8s.io/v1beta1"
  kind        = "CustomResourceDefinition"
```

But they should be (looking at your body, looks like your trying to make a ClusterIssuer)
```
  api_version = "certmanager.k8s.io/v1alpha1"
  kind ="ClusterIssuer"
```

**Comment by Tazer** [comment]
@timthesinner think my files are correct and CRD's isn't existing. Cause I did run the code at first and got the "already exist" error , deleted the CRD and then got above error. 

So what I'm trying to do is to create the definition of a Clusterissuer so I can create Clusterussuers later.

Basically it's from here: 
https://github.com/helm/charts/blob/master/stable/cert-manager/README.md#installing-the-chart

So cert-manager requires you to create CRD's before installing the helm chart. and what you need to create is in this file https://raw.githubusercontent.com/jetstack/cert-manager/release-0.6/deploy/manifests/00-crds.yaml

( It works fine when I run via kubectl )

**Comment by timthesinner** [comment]
@Tazer interesting, I was able to get a clean apply after I deleted the CRD from K8S.  Do you have a `depends_on` attribute defined to force dependency order?

Initial apply (CRD both exist)
```
Error: Error applying plan:

2 error(s) occurred:

* kubernetes_generic.issuer_crd: 1 error(s) occurred:

* kubernetes_generic.issuer_crd: customresourcedefinitions.apiextensions.k8s.io "issuers.certmanager.k8s.io" already exists
* kubernetes_generic.cr-clusterissuer: 1 error(s) occurred:

* kubernetes_generic.cr-clusterissuer: customresourcedefinitions.apiextensions.k8s.io "clusterissuers.certmanager.k8s.io" already exists
```
After removing CRD
```
kubernetes_generic.cloudflare-issuer: Creation complete after 0s (ID: certmanager.k8s.io/v1alpha1/deploy-dean-test/cloudflare-issuer)
kubernetes_generic.test: Creation complete after 0s (ID: certmanager.k8s.io/v1alpha1/terraform-example)

Apply complete! Resources: 4 added, 0 changed, 0 destroyed.
```

Here is my TF
```
resource "kubernetes_generic" "issuer_crd" {
    api_version = "apiextensions.k8s.io/v1beta1"
    kind ="CustomResourceDefinition"

    metadata {
        name = "issuers.certmanager.k8s.io"
        labels {
            app = "cert-manager"
            test = "la-la-connect-the-dots"
        }
    }

    yaml = <<EOF
group: certmanager.k8s.io
version: v1alpha1
names:
    kind: Issuer
    plural: issuers
scope: Namespaced
EOF
}

resource "kubernetes_generic" "cr-clusterissuer" {
  api_version = "apiextensions.k8s.io/v1beta1"
  kind        = "CustomResourceDefinition"

  metadata {
    name = "clusterissuers.certmanager.k8s.io"

    labels {
      app = "cert-manager"
      test = "la-la-connect-the-dots"
    }
  }

  yaml = <<EOF
  group: certmanager.k8s.io
  version: v1alpha1
  names:
    kind: ClusterIssuer
    plural: clusterissuers
  scope: Cluster
EOF
}

resource "kubernetes_generic" "test" {
    api_version = "certmanager.k8s.io/v1alpha1"
    kind ="ClusterIssuer"

    metadata {
        name = "terraform-example"
    }

    yaml = <<EOF
acme:
    email: email
    server: server
    privateKeySecretRef:
        name: secret-dev-test
    dns01:
        providers:
        - name: route53
        route53:
            hostedZoneID: zoneId
            accessKeyID: accessKey
            region: region
            secretAccessKeySecretRef:
                name: secret
                key: secret-access-key
EOF

    depends_on = [
        "kubernetes_generic.cr-clusterissuer"
    ]
}


resource "kubernetes_generic" "cloudflare-issuer" {
    api_version = "certmanager.k8s.io/v1alpha1"
    kind ="Issuer"

    metadata {
        name = "cloudflare-issuer"
        namespace = "deploy-dean-test"
    }

    yaml = <<EOF
  acme:
    email: xxx
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: asdf
    dns01:
      providers:
        - name: prod-clouddns
          cloudflare:
            email: xxx
            apiKeySecretRef:
              name: xxx
              key: api-key
EOF

    depends_on = [
        "kubernetes_generic.issuer_crd"
    ]
}
```

Once it has been deployed I always see the following for every `terraform apply` which is annoying but does not cause an issue as far as I can tell.
```
  ~ kubernetes_generic.cr-clusterissuer
      spec.names.listKind:                   "ClusterIssuerList" => ""
      spec.names.singular:                   "clusterissuer" => ""
      spec.transitent-delete.names.listKind: "" => "'ClusterIssuerList' --> ''"
      spec.transitent-delete.names.singular: "" => "'clusterissuer' --> ''"

  ~ kubernetes_generic.issuer_crd
      spec.names.listKind:                   "IssuerList" => ""
      spec.names.singular:                   "issuer" => ""
      spec.transitent-delete.names.listKind: "" => "'IssuerList' --> ''"
      spec.transitent-delete.names.singular: "" => "'issuer' --> ''"
```

**Comment by Tazer** [comment]
Cool @timthesinner,

Trying some more, I get quite an interesting output. 

Cause just tried to rerun with the new version and got `kubernetes_generic.cr-clusterissuer: customresourcedefinitions.apiextensions.k8s.io "clusterissuers.certmanager.k8s.io" already exists`

Even without a successful run, So I tried ` kubectl delete crd clusterissuers.certmanager.k8s.io` with response: `customresourcedefinition.apiextensions.k8s.io "clusterissuers.certmanager.k8s.io" deleted`

And did another run then I got the EOF error. and then I ran again and got `kubernetes_generic.cr-clusterissuer: customresourcedefinitions.apiextensions.k8s.io "clusterissuers.certmanager.k8s.io" already exists`

So seems the "create" is working but something with the response? Is there a good way I can debug it a bit better?

**Comment by timthesinner** [comment]
Can you put your TF (redacted and focused on just your generic resources) in a gist for me?  

You can run with `TF_LOG=DEBUG terraform apply` for more output.  Will be honest that's a weak area in this PR, I have been going into the code and adding log statements to figure out what's going on.

**Comment by Tazer** [comment]
@timthesinner here you go https://gist.github.com/Tazer/1b0d8b1ff0c99b2e7bbb35e770061756

**Comment by yacut** [comment]
@timthesinner @Tazer any update on this?

**Comment by Tazer** [comment]
The current status is that,

Creating crds defination doesn't really work for me. ( Solved it by running kubectl via local exec for those) but works fine when creating crd resources.

**Comment by yacut** [comment]
@timthesinner Are you still working on it? Do you need some help?

**Comment by barryib** [comment]
Any update on this ? Any chance to see this merged ?

**Comment by JulienBreux** [comment]
Hi @timthesinner,

Do you need some help?

Tell me how can I help you?

Cheers

**Comment by cwebbtw** [comment]
Is there an update on this? It would be great to have support for custom resource definitions, is there any support that can be provided on this PR to understand what work is left to do.

**Comment by alexsomesan** [comment]
Quick update here: the recently released v0.3.1 of the Kubernetes Alpha provider has quite usable support for CRDs. I would encourage everyone to give that a try a provide us with feedback. That would help us to graduate that provider to GA as soon as possible.

**Comment by jrhouston** [comment]
Closing this as `kubernetes_manifest` is now in the provider.

**Pull request closed without merging**
