### PR TITLE
Add behavior field to horizontal pod autoscaler

### PR DESCRIPTION
**Pull request by skolodyazhnyy**
### Description

Add support for behavior field in horizontal_pod_autoscaler as requested in #1029 

### Acceptance tests
- [x] Have you added an acceptance test for the functionality being added?
- [x] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccKubernetesHorizontalPodAutoscalerV2.*'

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ".../terraform-provider-kubernetes/kubernetes" -v -run=TestAccKubernetesHorizontalPodAutoscalerV2.* -timeout 120m
=== RUN   TestAccKubernetesHorizontalPodAutoscalerV2_basic
--- PASS: TestAccKubernetesHorizontalPodAutoscalerV2_basic (1.86s)
PASS
ok      github.com/hashicorp/terraform-provider-kubernetes/kubernetes   4.458s
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-kubernetes/blob/master/CHANGELOG.md):

```release-note
- Add `behavior` field to horizontal pod autoscaler
```

### References

- User guide https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-configurable-scaling-behavior
- Reference https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#horizontalpodautoscalerspec-v2beta2-autoscaling
- Add support for metrics field in horizontal_pod_autoscaler https://github.com/hashicorp/terraform-provider-kubernetes/pull/773

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Comment by komljen** [comment]
The behavior HPA field is in beta from k8s 1.18, meaning it is available by default. And most cloud providers already support 1.18, so this PR should go in. Thanks, @skolodyazhnyy!

**Comment by komljen** [comment]
@alexsomesan can you help with the review?

**Comment by skolodyazhnyy** [comment]
@alexsomesan @komljen Is there anything I can do to help with this getting merged?

**Comment by bmaehr** [comment]
@jrhouston Could you please have a look on this?

**Comment by bmaehr** [comment]
@jrhouston Ok, perhaps I have to be more clear: Is it possible to merge this pull request so it is included into the next version?

**Review by jrhouston — CHANGES_REQUESTED** [review]
This PR looks good but we need to add the behaviour field to the documentation page for horizontal_pod_autoscaler.

**Comment by tommynguyen-vungle** [comment]
@jrhouston @skolodyazhnyy Anything I could help on the documentation part?

**Comment by skolodyazhnyy** [comment]
It's been a while for this PR, I've used workaround for almost a year now 😅  

But sure, what do I need to do?

**Comment by george-zubrienko** [comment]
@skolodyazhnyy I think you need to extend this [doc](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/website/docs/r/horizontal_pod_autoscaler.html.markdown), describing the `behavior` field and PR will get merged

**Comment by tommynguyen-vungle** [comment]
@skolodyazhnyy have you had a chance to look at it?

**Comment by tommynguyen-vungle** [comment]
@jrhouston looks like @skolodyazhnyy is not so active at the moment. Could I take over the PR?

**Comment by jrhouston** [comment]
@tommynguyen-vungle You have to be a maintainer on the repo to take over a PR. If you want, you can open your branch with the docs as a new PR against this repo I can approve it and make you co-author.

**Comment by skolodyazhnyy** [comment]
Sorry, I was away for a while. I have merged doc changes.

**Comment by tommynguyen-vungle** [comment]
cool, thanks @jrhouston @skolodyazhnyy !

**Comment by skolodyazhnyy** [comment]
@tommynguyen-vungle we are missing CLA on your side, see Github status checks

**Comment by tommynguyen-vungle** [comment]
@skolodyazhnyy signed

**Comment by skolodyazhnyy** [comment]
@tommynguyen-vungle could you sign using @tuannvm account? CLA is still pending.

**Comment by tuannvm** [comment]
@skolodyazhnyy all good

**Comment by tommynguyen-vungle** [comment]
@jrhouston could you have a look again pls? Thanks

**Comment by tuannvm** [comment]
@skolodyazhnyy @jrhouston while waiting for this PR to be merged, I've managed to make it work using the generic `kubernetes_manifest` resource. See https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest

```
provider "kubernetes" {
  experiments {
    manifest_resource = true
  }
}

resource "kubernetes_manifest" "hpa" {

  for_each = local.applications
  manifest = {
    "apiVersion" = "autoscaling/v2beta2"
    "kind"       = "HorizontalPodAutoscaler"
    "metadata" = {

      "name"      = each.value["deployment_name"]
      "namespace" = each.value["namespace"]
    }
    "spec" = {
      "behavior" = {
        "scaleDown" = {
          "policies" = [
            {
              "periodSeconds" = each.value["scale_down_period_seconds"]
              "type"          = "Percent"
              "value"         = each.value["scale_down_pct"]
            },
            {
              "periodSeconds" = each.value["scale_down_period_seconds"]
              "type"          = "Pods"
              "value"         = 1
            },
          ]
          "selectPolicy"               = "Max"
          "stabilizationWindowSeconds" = each.value["scale_down_stabilization_window_seconds"]
        }
        "scaleUp" = {
          "policies" = [
            {
              "periodSeconds" = each.value["scale_up_period_seconds"]
              "type"          = "Percent"
              "value"         = each.value["scale_up_pct"]
            },
            {
              "periodSeconds" = each.value["scale_up_period_seconds"]
              "type"          = "Pods"
              "value"         = 1
            },
          ]
          "selectPolicy"               = "Max"
          "stabilizationWindowSeconds" = each.value["scale_up_stabilization_window_seconds"]
        }
      }
      "maxReplicas" = each.value["max_replicas"]
      "metrics" = [
        {
          "external" = {
            "metric" = {
              "name" = "${each.value["app_name"]}_requests_per_pod"
            }
            "target" = {
              "type"  = "Value"
              "value" = each.value["threshold"]
            }
          }
          "type" = "External"
        },
      ]
      "minReplicas" = each.value["min_replicas"]
      "scaleTargetRef" = {
        "apiVersion" = "apps/v1"
        "kind"       = "Deployment"
        "name"       = each.value["deployment_name"]
      }
    }
  }
}
```

**Comment by curtbushko** [comment]
Eagerly awaiting this PR. These behavior fields would be very useful for helping with pod churn in our clusters.

**Comment by skolodyazhnyy** [comment]
@curtbushko AFAIK, [Hashicorp is not doing PR reviews](https://github.com/hashicorp/terraform/commit/6562466c32a8750d7a71a6cc6232e6b5a28fe13a), so maybe best to go for generic manifest as suggested by @tuannvm.

**Comment by jrhouston** [comment]
Thanks for the patience here folks. I've made one small change to this PR which is to make `metric` computed – if you specify `behaviour` with no metrics the API will add a default metric of 80% average CPU which was causing a diff after creating the HPA. 

I'll merge this after the checks are passing.

**Comment by curtbushko** [comment]
@jrhouston Thanks!  Just in time for me to use it and clean up my cluster scaling!  :)

**Pull request merged**
