### PR TITLE
Fix metrics hpa diffbug

### LINKED ISSUE #1188: Is it intentional that order of metrics matter on HPAs?
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: v0.14.7
Kubernetes provider version: v2.0.2
Kubernetes version:  v1.19
```

### Affected Resource(s)
- kubernetes_horizontal_pod_autoscaler
- kubernetes_service
- kubernetes_deployment

Using this with AWS, not sure if that matters.

### Terraform Configuration Files
```hcl

resource "kubernetes_deployment" "my_app_deployment" {
	metadata {
		name = "my-app-deployment"
		labels = {
			app = "my-app"
		}
	}

	spec {
		revision_history_limit = 3

		selector {
			match_labels = {
				app = "my-app"
			}
		}

		template {
			metadata {
				labels = {
					app = "my-app"
				}
			}

			spec {
				container {
					name = "my-app"
					image = "IMAGE_URL"
					image_pull_policy = "Always"

					port {
						container_port = 80
					}

					resources {
						requests = {
							cpu = "200m"
							memory = "200Mi"
						}
						limits = {
							cpu    = "600m"
							memory = "600Mi"
						}
					}
				}
			}
		}
	}
}

resource "kubernetes_service" "my_app_service" {
	metadata {
		name = "my-app-service"
	}

	spec {
		type = "ClusterIP"
		selector = {
			app = "my-app"
		}

		port {
			protocol = "TCP"
			port = 80
			target_port = 80
		}
	}
}

resource "kubernetes_horizontal_pod_autoscaler" "my_app_hpa" {
	metadata {
		name = "my-app-hpa"
	}

	spec {
		min_replicas = 1
		max_replicas = 5

		scale_target_ref {
			api_version = "apps/v1"
			kind = "Deployment"
			name = "my-app-deployment"
		}

		metric {
			type = "Resource"

			resource {
				name = "cpu"

				target {
					type = "Utilization"
					average_utilization = 60
				}
			}
		}

		metric {
			type = "Resource"

			resource {
				name = "memory"

				target {
					type = "Utilization"
					average_utilization = 60
				}
			}
		}

	}
}
```

### Steps to Reproduce
1. `terraform apply` (type yes)
2. Run `terraform apply` again without changing config

### Expected Behavior
No changes should be listed as the config is unchanged.

### Actual Behavior
Even though config is unchanged the actions below are listed on every `terraform apply`. If i change the order of metrics in the above config the changes to list memory above cpu, this does not happen.

```
  # kubernetes_horizontal_pod_autoscaler.my_app_deployment will be updated in-place
  ~ resource "kubernetes_horizontal_pod_autoscaler" "my_app_hpa" {
        id = "default/myapp-hpa"


      ~ spec {
            # (3 unchanged attributes hidden)

          ~ metric {
                # (1 unchanged attribute hidden)

              ~ resource {
                  ~ name = "memory" -> "cpu"

                    # (1 unchanged block hidden)
                }
            }
          ~ metric {
                # (1 unchanged attribute hidden)

              ~ resource {
                  ~ name = "cpu" -> "memory"

                    # (1 unchanged block hidden)
                }
            }

            # (1 unchanged block hidden)
        }
        # (1 unchanged block hidden)
    }
Plan: 0 to add, 1 to change, 0 to destroy.
```

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by BBBmau**
### Description

This PR changes the attribute type of `metrics` in horizontal pod autoscaler to `Set` in order to prevent Diffs from appearing despite their not being any change in the tfconfig. (Diff comes from out of order metrics list, using a set type for metrics would prevent this.)

Fixes #1188 

### Acceptance tests
- [ ] Have you added an acceptance test for the functionality being added?
- [ ] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
$ make testacc TESTARGS="-run TestAccKubernetesHorizontalPodAutoscalerV2Beta2_basic"

...
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/CHANGELOG.md):

```release-note
`kubernetes/resource_horizontal_pod_autoscaler.go`: Change Lists to Set in metrics to prevent out of order metrics Diff
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Comment by BBBmau** [comment]
I'll need some advice on how to handle a bug when changing from `Lists` to `Sets`

It looks to solve the problem however I noticed that when attempting to patch the resource, it produces an empty metric value in the set. Resulting in
```bash
 Error: Failed to update horizontal pod autoscaler: HorizontalPodAutoscaler.autoscaling "my-app-hpa" is invalid: [spec.metrics[0].type: Required value: must specify a metric source type, spec.metrics[0].type: Unsupported value: "": supported values: "ContainerResource", "External", "Object", "Pods", "Resource"]
 ```
 due to their being an empty metric block being added to the set despite not their being one in the config. This can be seen when applying the configs from `TestAccKubernetesHorizontalPodAutoscalerV2Beta2_basic`

1.  Running basic config
2. Running modified config

will result in the Error.

I'm not sure where exactly the empty `metric` block is being added in the Update function. I'll need some input on this. @jrhouston @alexsomesan

**Comment by BBBmau** [comment]
This is currently Blocked after discussing this issue further with @alexsomesan. We discovered that the extra empty metric value comes from `d.Get("metrics").(*Schema.Set)` which comes from the terraform-plugin-sdk repo. I'll be making an issue in that repo bringing up the block that I'm facing for fixing the metrics HPA Diff Bug

**Comment by jrhouston** [comment]
Instead of changing the type here, couldn't we just use a [DiffSuppressFunc](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#SchemaDiffSuppressFunc) on this attribute, sort the old and new values and if they're the same then suppress the diff?

**Comment by BBBmau** [comment]
Closing this since I don't intend to work on this PR. In the future I'd want to start over and go at it in a different way.

**Pull request closed without merging**
