### PR TITLE
csi pod volume

### PR DESCRIPTION
**Pull request by bsomes**
### Description
Get ephemeral CSI volumes working and update schema to reflect the differences in the API between ephemeral and persistent CSI Volumes

I would like some feedback regarding how to make acceptance tests for this. Finding this required installing a Helm chart for Azure keyvault integration specifically, and that does not seem like a good way to go about acceptance testing this change.
Output from acceptance testing:

### Acceptance tests
- [x] Have you added an acceptance test for the functionality being added?
- [x] Have you run the acceptance tests on this branch?

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-kubernetes/blob/master/CHANGELOG.md):

```release-note
...Fix CSI ephemeral pod volumes
```

### References
#1086 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Comment by oktapodia** [comment]
Looks promising, any news on that?

**Comment by alexsomesan** [comment]
Thanks a lot for contributing this!
Would you mind exercising the new attribute in one ore more of the acceptance tests in addition to the unit tests you already included?

Thanks!

**Comment by bsomes** [comment]
Awesome! Thanks for the tips. I'll take a crack at an acceptance test and we'll see how it goes.

**Comment by bsomes** [comment]
didn't mean to do all that Git shenanigans but I think I've got a test in there now. I needed to enable csi-hostpath-driver minikube add-on to get it to work. If that's a problem then I can look into setting up the test without that. Also it looks like @oktapodia has done some work on getting Travis to pick this up so maybe that PR can supersede this one.

**Comment by oktapodia** [comment]
Exactly, I will just keep the GitHub actions work in my pr, I did not think you were on it, sorry about that, will update it tomorrow

**Comment by bsomes** [comment]
> Exactly, I will just keep the GitHub actions work in my pr, I did not think you were on it, sorry about that, will update it tomorrow

No you were correct, I was not on it.

**Comment by oktapodia** [comment]
Can you make your PR in "Ready to review" state please? Looks like it is not a draft anymore 💪

**Comment by oktapodia** [comment]
@alexsomesan do you think this can be merge for the next release?

**Comment by bsomes** [comment]
Do I need to do anything else for this or is it good to go?

**Comment by rtrive** [comment]
Any news on merge?

**Comment by jffaust** [comment]
@alexsomesan can we proceed with the merge?

**Comment by mattduguid** [comment]
hi @jffaust @alexsomesan do you know the time frame for when this will be available in the provider?

**Comment by shicholas** [comment]
I'd love to see this mergede, thanks @bsomes!

**Comment by rkennedy-tpl** [comment]
is this still outstanding? I am interested in using `vault-csi` and landed on this issue after searching some error messages.

**Comment by sombralibre** [comment]
Hi there, any ETA to merge this PR, for now the workaround is to use `kubernetes_manifest` resource.

**Comment by dghubble** [comment]
What are the remaining tasks for this change to be accepted?

**Comment by salecharohit** [comment]
Please merge this issue as its not mounting CSI volumes which are required for loading secrets through the `secrets-store.csi.k8s.io` workaround is to use `kubectl_manifest` for now.
The volumes defintion is absent in the generated k8s file

**Review by arybolovlev — APPROVED** [review]
Thank you for fixing this issue @bsomes! Everything looks good and we are good to go ahead and merge your changes.

Great job and thanks for your contribution!

**Pull request merged**
