### PR TITLE
`v3`: upgrade kubernetes to `v1.31.2` and Go `v1.23`

### PR DESCRIPTION
**Pull request by sheneska**
### Acceptance tests
- [ ] Have you added an acceptance test for the functionality being added?
- [ ] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/CHANGELOG.md):

```release-note
...
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Comment by BBBmau** [comment]
We'll want to wait to upgrade the kubernetes version since they'll be releasing v1.31 soon (August 13) 

https://www.kubernetes.dev/resources/release/#summary

**Comment by BBBmau** [comment]
failing tests are related to k8s client go dropping support for `PodSecurityPolicy`. Mentioned in a previous issue:

https://github.com/hashicorp/terraform-provider-kubernetes/issues/2234#issuecomment-1690187484

**Comment by coryflucas** [comment]
Do you plan to update the version of k8s used in the acceptance tests as part of this? I was hoping to pick up #2446 but the current version of k8s used in the tests won't support the feature.

**Comment by BBBmau** [comment]
> Do you plan to update the version of k8s used in the acceptance tests as part of this? I was hoping to pick up #2446 but the current version of k8s used in the tests won't support the feature.

Thanks for bringing this up, from this i noticed that we explicitly set the PR kind version to be `0.20.0`, thus using `v1.27` k8s.

We'll want to also update the workflow to match the k8s upgrade, though it would be nice to include a matrix to test across different versions, similar to how we handle tests across different tf versions in the helm provider: https://github.com/hashicorp/terraform-provider-helm/blob/main/scripts/get-version-matrix.sh

Interested in working on it @coryflucas? The issue you mentioned has a PR currently opened and I plan on wrapping that one since it's only missing the tests.

**Comment by coryflucas** [comment]
That seems doable. I'll open an issue for that with some follow up questions I have and get started on it.

**Comment by BBBmau** [comment]
@JaylonmcShan03  We'll want to also make changes so that we're upgrading to Go `1.23` as well as the latest k8s plugin go version which is `v1.31.2`

https://pkg.go.dev/k8s.io/kubernetes?tab=versions

We may want to even consider upgrading to `v1.32.1` when the time comes before merging and cutting a v3 provider release. Looks like the next release will be December 11th for `v1.32.0` https://www.kubernetes.dev/resources/release/

**Review by BBBmau — APPROVED** [review]
Ready to merge! We'll need to address the errors caught from CI before we continue with supporting major release features.

**Pull request merged**
