### PR TITLE
r/deployment - wait for deployment to delete

### PR DESCRIPTION
**Pull request by DrFaust92**
### Description

Add wait logic for deployment resource to properly delete (similar to other resources like CSI Driver and stateful set)

### Acceptance tests
- [x] Have you added an acceptance test for the functionality being added?
- [x] Have you run the acceptance tests on this branch? (If so, please include the test log in a gist)

```
--- PASS: TestAccKubernetesDeployment_basic (91.68s)
--- PASS: TestAccKubernetesDeployment_with_share_process_namespace (17.99s)
--- PASS: TestAccKubernetesDeployment_no_rollout_wait (19.82s)
--- PASS: TestAccKubernetesDeployment_with_deployment_strategy_rollingupdate_max_surge_30perc_max_unavailable_40perc (19.20s)
--- PASS: TestAccKubernetesDeployment_with_deployment_strategy_rollingupdate_max_surge_200perc_max_unavailable_0perc (21.52s)
--- PASS: TestAccKubernetesDeployment_with_deployment_strategy_rollingupdate_max_surge_0_max_unavailable_1 (31.07s)
--- PASS: TestAccKubernetesDeployment_with_deployment_strategy_rollingupdate_max_surge_1_max_unavailable_0 (18.30s)
--- PASS: TestAccKubernetesDeployment_with_deployment_strategy_rollingupdate_max_surge_1_max_unavailable_2 (17.79s)
--- PASS: TestAccKubernetesDeployment_with_deployment_strategy_recreate (17.67s)
--- PASS: TestAccKubernetesDeployment_with_host_aliases (24.91s)
--- PASS: TestAccKubernetesDeployment_config_with_automount_service_account_token (31.38s)
```

### References

https://github.com/DrFaust92/terraform-kubernetes-ebs-csi-driver/issues/2

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Comment by eddy-curv** [comment]
looks promising, can it be released in 1.12.1?

**Comment by charlex** [comment]
Does anyone know if 1.12.1 is being held, or does it just need to be tagged and released?

**Comment by aareet** [comment]
@charlex we're working to tag/release this week

**Comment by charlex** [comment]
> @charlex we're working to tag/release this week

Thanks @aareet. Looking forward to the days where I don't have to apply plans twice for a deployment :)

**Comment by charlex** [comment]
👀

https://github.com/hashicorp/terraform-provider-kubernetes/releases/tag/v1.13.0

**Pull request merged**
